#!/bin/bash

rc-update add lvm boot
rc-update add cupsd sysinit
rc-update add device-mapper boot
rc-update add dmcrypt boot
rc-update add mdraid boot
rc-update add gpm sysinit
rc-update add NetworkManager default
rc-update add autoconfig default
rc-update add hwsetup default
rc-update add unmute default
rc-update add autorun default
rc-update add dbus default
rc-update add dostartx default
rc-update add load-fonts-keymaps default
rc-update add netconfig2 default
rc-update add tigervnc default
rc-update add consolekit default
rc-update add syslog-ng default
rc-update del keymaps boot
rc-update del save-keymaps boot
rc-update add sysresccd default

CHECK_XDM=$(grep exit\ 0 /etc/init.d/xdm|wc -l)
if [ ${CHECK_XDM} -lt 1 ]; then sed -i '2 i\exit 0' /etc/init.d/xdm;fi

CHECK_XDM_SETUP=$(grep exit\ 0 /etc/init.d/xdm-setup|wc -l)
if [ ${CHECK_XDM_SETUP} -lt 1 ]; then sed -i '2 i\exit 0' /etc/init.d/xdm-setup;fi
